In [3]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
import sklearn

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
train = pd.read_csv('example_train.csv')

In [10]:
train['Class'] = train['Class'].apply(lambda x: 1 if x=='education' else 0)

In [11]:
train

Document  Class
0         Upgrad is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [12]:
train_array = train.values

X_train = train_array[:,0]
y_train = train_array[:,1]
y_train = y_train.astype('int')
print(X_train)
print(y_train)

['Upgrad is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
[1 1 1 0 0]


In [14]:
vec = CountVectorizer()

In [15]:
vec.fit(X_train)
vec.vocabulary_

{'upgrad': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [16]:
vec2 = CountVectorizer(stop_words='english')

In [17]:
vec2.fit(X_train)
vec2.vocabulary_

{'upgrad': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [19]:
X_transform = vec2.transform(X_train)
print(X_transform)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [20]:
test = pd.read_csv('example_test.csv')

In [21]:
test['Class'] = test['Class'].apply(lambda x: 1 if x=='education' else 0)

In [22]:
test_array = test.values

X_test = test_array[:,0]
y_test = test_array[:,1]
y_test = y_test.astype('int')
print(X_test)
print(y_test)

['very good educational institution']
[1]


In [24]:
X_test_transform = vec2.transform(X_test)
print(X_test_transform)

  (0, 2)	1
  (0, 4)	1
  (0, 7)	1


In [25]:
mnb = MultinomialNB()

In [27]:
mnb.fit(X_transform, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [28]:
mnb.predict_proba(X_test_transform)

array([[0.32808399, 0.67191601]])

In [29]:
bnb = BernoulliNB()

In [30]:
bnb.fit(X_transform, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [31]:
bnb.predict_proba(X_test_transform)

array([[0.2326374, 0.7673626]])